inherit_from: .rubocop_todo.yml

AllCops:
  Excludes:
    - db/schema.rb
    - db/migrate/**
    - vendor/bundle/**/*
    - node_modules/**/*

Style/BlockLength:
  Exclude:
    - 'spec/**/*'
    - Guardfile

Style/Documentation:
  Exclude:
    - 'app/controllers/*'
    - 'app/helpers/*'
    - 'app/models/*'
    - 'app/mailers/*'
    - 'config/application.rb'
